Registering TEAM codeAR
ISTESRMNCR/CODE-CAMP-2020 pull request #20
Opened 2020-07-19 10:07 UTC by arnav-snowleo

# Application for Registering Team to CODE CAMP 1.0

This pull request template helps you complete an application to the **CODE CAMP 1.0 HACKATHON**. Use the checklist below to verify that you have followed the instructions correctly. 

**(Put x inside [] like [x])**

## Select the type of Pull Request

[] Registration Pull request.

[] Submission Pull request.

## Checklist ✅  

- [] I have read the instructions on the README file before submitting my application and gone through [CODE_OF_CONDUCT](). 
- [] I have Submitted my team's details by making a folder of my team as instructed in [How to send Pull Request page](https://codecamphackathon.netlify.app/makingRegistration/).
- [] I have used the Markdown file template to add my information for the Hackathon.
- [] I have given all the necessary details as mentioned in template index.md file and the details are correct and best to my knowledge.
- [] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [] I understand I should not tag or add a reviewer to this Pull Request.
- [] I understand the Details added to the template will be used as a means of communication at the time of result declaration.
- [] I have added the [event](https://calendar.google.com/calendar/r/eventedit/copy/MHUzM2pvaDQwM3R1cDdxMmdjMmQyYjZpaHAgN3NhMzI0N2FpMzkzczAzbWo0YWMxNWVzdG9AZw) to my calendar.

2020-07-19 10:14 UTC, Uyadav207 commented
@arnav-snowleo , Everthing Looks great. please can you fill the application checklist .

put x between [] like this [x]

2020-07-19 10:15 UTC, Uyadav207 approved these changes

2020-07-19 10:27 UTC, arnav-snowleo commented
Greetings,

I have made the required changes.
Let me know if something is missing.

Regards
Arnav

On Sun 19 Jul, 2020, 3:45 PM Utkarsh Yadav, <notifications@github.com>
wrote:

> *@Uyadav207* approved this pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ISTESRMNCR/CODE-CAMP-2020/pull/20#pullrequestreview-451117899>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQKF2QDRPLMFXDG6NDGSDITR4LBVDANCNFSM4PBEUTCA>
> .
>

2020-07-19 10:29 UTC, Uyadav207 commented
You haven't checked the list above 

wait I will edit it.

2020-07-19 10:33 UTC, Uyadav207 requested changes

2020-07-19 10:33 UTC, Uyadav207 commented on content/teams/codeAR/index.md
> +
Mention member 2 Github link. same as you have mention for Leader.

2020-07-19 10:33 UTC, Uyadav207 commented on content/teams/codeAR/index.md
> +_**GitHub-Link**_ :   " https://github.com/arnav-snowleo/ScannerApp "
No quotes required .

2020-07-19 10:33 UTC, Uyadav207 commented on content/teams/codeAR/index.md
> +_**Tech-Stack-Used**_ :   The Mobile App will be built in Flutter framwork with Dart Language
Minor Typos in here . write Framework like this

2020-07-19 10:33 UTC, Uyadav207 commented on content/teams/codeAR/index.md
> +---
one line of spacing needed.

2020-07-19 10:34 UTC, Uyadav207 commented
@arnav-snowleo , make these more change and then your team is ready to roll.

2020-07-19 10:58 UTC, arnav-snowleo commented
Did the required changes.

On Sun 19 Jul, 2020, 4:04 PM Utkarsh Yadav, <notifications@github.com>
wrote:

> @arnav-snowleo <https://github.com/arnav-snowleo> , make these more
> change and then your team is ready to roll.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ISTESRMNCR/CODE-CAMP-2020/pull/20#issuecomment-660623137>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQKF2QBDWIPH4Q2CAERZ2LDR4LD4LANCNFSM4PBEUTCA>
> .
>

2020-07-19 11:05 UTC, Uyadav207 approved these changes

2020-07-19 11:05 UTC, Uyadav207 commented
@arnav-snowleo 
 Hola  👋 ! Team  you have successfully completed the `First phase of the Hackathon`. ( We have successfully merged your PR for Registration ). 
Now we Request you to join your Team to our [**CODE CAMP GROUP 1**](https://chat.whatsapp.com/EowU6RVas3QCmtEs7q7L0H).
And you can start making your project from `21th July,2020`.
We have attached important Links. 

[**TimeLine**](https://codecamphackathon.netlify.app/TimeLine/)
[**Rule Book**](https://codecamphackathon.netlify.app/RuleBook/)
[**Prizes**](https://codecamphackathon.netlify.app/Prizes/)

See you there!
@ISTESRMNCR

2020-07-19 11:09 UTC, merged

2020-07-20 11:54 UTC, Uyadav207 commented
@arnav-snowleo , please join whatsapp group and say `Team name and we are in`

2020-07-21 06:53 UTC, arnav-snowleo commented
Where do I find the Whatsapp group invite link?

On Mon, Jul 20, 2020 at 5:24 PM Utkarsh Yadav <notifications@github.com>
wrote:

> @arnav-snowleo <https://github.com/arnav-snowleo> , please join whatsapp
> group and say Team name and we are in
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ISTESRMNCR/CODE-CAMP-2020/pull/20#issuecomment-660981564>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQKF2QAKCS6ODA4SHHB3GTLR4QWATANCNFSM4PBEUTCA>
> .
>

2020-07-21 07:16 UTC, Uyadav207 commented
@arnav-snowleo , [**CODE CAMP GROUP 1**](https://chat.whatsapp.com/EowU6RVas3QCmtEs7q7L0H). this was the link given early. kindly be active.

2020-07-21 07:17 UTC, Uyadav207 commented
and after joining the group please reply your team name, and also say we are in NOW